# -*- coding: utf-8 -*-
"""help

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdolywIm0t0xuxQSQBf0UWO8uqGR7uRa
"""

def help (benar, panggil): #bisa dipanggil di setiap momen dengan kode '-help'

  benar = True #buat bedain user sama admin. user diseting false
  
  if benar:
    print('============ HELP ============')
    print('1. register - Untuk melakukan registrasi user baru')    
    print('2. login - Untuk melakukan login ke dalam sistem')    
    print('3. tambah_game - Untuk menambah game yang dijual pada toko')    
    print('4. list_game_toko - Untuk melihat list game yang dijual pada toko')    
    number = int(input())
    if number == 1:
      print('')
    elif number == 2:
      print('')
    elif number == 3:
      print('')
    elif number == 4:
      print('')

  else:
    print('============ HELP ============')
    print('1. login - Untuk melakukan login ke dalam sistem')
    print('2. list_game_toko - Untuk melihat list game yang dijual pada toko')    
    number = int(input())
    if number == 1:
      print('')
    elif number == 2:
      print('')